/**
 * Emitters (#237): a resolved corpus → committed artifacts under
 * `src/wire/generated/<era>/`.
 *
 * Per grammar `<name>.abnf`:
 *   - `<name>.ts`          — anchored `*_RE` regexes for every terminal rule,
 *                            `*_VALUES`/type enums for closed literal sets, and
 *                            `*_MIN_LEN`/`*_MAX_LEN` consts for `;@bound` rules.
 *   - `<name>.schema.json` — JSON-Schema `pattern` (+ `minLength`/`maxLength`,
 *                            `enum`) fragments keyed by rule name.
 * Plus an `index.ts` barrel and a `README.md` generated-notice.
 *
 * Output is a pure function of the grammar text — no timestamps, no absolute
 * paths — so two runs are byte-identical (the determinism acceptance).
 */

import type { Corpus } from "./resolver";
import type { Grammar } from "./ast";
import { ruleRegex, literalSet } from "./regex";

export interface OutFile {
  path: string; // relative to the generated-era root
  content: string;
}

const GEN_NOTICE = "GENERATED by tools/abnf-gen — DO NOT EDIT. Source of truth:";

function constName(rule: string): string {
  return rule.replace(/-/g, "_").toUpperCase();
}
function typeName(rule: string): string {
  return rule.split("-").map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");
}

interface RuleArtifact {
  rule: string;
  pattern: string; // anchored ^...$
  enumValues: string[] | null;
  min: number | null;
  max: number | null;
}

function artifactsFor(corpus: Corpus, g: Grammar): RuleArtifact[] {
  const boundByRule = new Map(g.bounds.map((b) => [b.rule, b]));
  return g.order.map((name) => {
    const rule = g.rules.get(name)!;
    const b = boundByRule.get(name);
    return {
      rule: name,
      pattern: ruleRegex(corpus, g, rule.node),
      enumValues: literalSet(corpus, g, rule.node),
      min: b ? b.min : null,
      max: b ? b.max : null,
    };
  });
}

function emitTs(g: Grammar, arts: RuleArtifact[]): string {
  const lines: string[] = [];
  lines.push(`// ${GEN_NOTICE} specs/grammar/${g.file}`);
  lines.push(`// Regenerate: bun tools/abnf-gen   (drift-gated by: bun tools/abnf-gen --check)`);
  lines.push("");
  for (const a of arts) {
    const CN = constName(a.rule);
    lines.push(`/** \`${a.rule}\` — specs/grammar/${g.file} */`);
    lines.push(`export const ${CN}_RE = /${a.pattern}/;`);
    if (a.enumValues) {
      const vals = a.enumValues.map((v) => JSON.stringify(v)).join(", ");
      lines.push(`export const ${CN}_VALUES = [${vals}] as const;`);
      lines.push(`export type ${typeName(a.rule)} = (typeof ${CN}_VALUES)[number];`);
    }
    if (a.min !== null) lines.push(`export const ${CN}_MIN_LEN = ${a.min};`);
    if (a.max !== null) lines.push(`export const ${CN}_MAX_LEN = ${a.max};`);
    lines.push("");
  }
  return lines.join("\n");
}

function emitSchema(g: Grammar, arts: RuleArtifact[]): string {
  const obj: Record<string, unknown> = {
    $comment: `${GEN_NOTICE} specs/grammar/${g.file}`,
  };
  for (const a of arts) {
    const frag: Record<string, unknown> = { pattern: a.pattern };
    if (a.min !== null) frag.minLength = a.min;
    if (a.max !== null) frag.maxLength = a.max;
    if (a.enumValues) frag.enum = a.enumValues;
    obj[a.rule] = frag;
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

function nsName(base: string): string {
  const parts = base.split("-");
  return parts[0]! + parts.slice(1).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");
}

function emitBarrel(files: string[]): string {
  // Namespace per grammar — the corpus reuses rule names across files (`lower`,
  // `classification`, `sovereignty-mode`, …), so a flat `export *` collides.
  const lines = [`// ${GEN_NOTICE} specs/grammar/*.abnf`, ""];
  for (const f of files.sort()) lines.push(`export * as ${nsName(f)} from "./${f}";`);
  lines.push("");
  return lines.join("\n");
}

function emitReadme(era: string, grammarFiles: string[]): string {
  return [
    `# src/wire/generated/${era}`,
    "",
    `${GEN_NOTICE} specs/grammar/*.abnf`,
    "",
    "These files are produced by \`bun tools/abnf-gen\` from the normative ABNF",
    "grammars. **Do not hand-edit** — change the \`.abnf\` and regenerate. CI runs",
    "\`bun tools/abnf-gen --check\` and fails on drift.",
    "",
    `Era: \`${era}\` — the ratified (flag-day) forms, staged per design-rfc-alignment.md D6.`,
    "",
    "Sources:",
    ...grammarFiles.sort().map((f) => `- \`specs/grammar/${f}\` → \`${f.replace(/\.abnf$/, "")}.ts\` + \`.schema.json\``),
    "",
  ].join("\n");
}

/** Produce every output file for an era (paths relative to the era root). */
export function emitAll(corpus: Corpus, era: string): OutFile[] {
  const out: OutFile[] = [];
  const tsBases: string[] = [];
  for (const g of [...corpus.grammars].sort((a, b) => a.file.localeCompare(b.file))) {
    const base = g.file.replace(/\.abnf$/, "");
    const arts = artifactsFor(corpus, g);
    out.push({ path: `${base}.ts`, content: emitTs(g, arts) });
    out.push({ path: `${base}.schema.json`, content: emitSchema(g, arts) });
    tsBases.push(base);
  }
  out.push({ path: "index.ts", content: emitBarrel(tsBases) });
  out.push({ path: "README.md", content: emitReadme(era, corpus.grammars.map((g) => g.file)) });
  return out.sort((a, b) => a.path.localeCompare(b.path));
}
